import { Task } from './types';

export const initialTasks: Task[] = [
  {
    id: 't1',
    title: 'Karate Conditioning',
    category: 'TRAINING',
    day: 'Monday',
    time: '07:00',
    duration: '60 min',
    colorTint: 'bg-[#fce7f3]',
    subtitle: '4 sets • 85% load',
  },
  {
    id: 't2',
    title: 'Organic Chemistry II',
    category: 'STUDYING',
    day: 'Monday',
    time: '10:00',
    duration: '120 min',
    colorTint: 'bg-[#e0f2fe]',
    subtitle: 'Carbonyl reactions • 120m',
  },
  {
    id: 't3',
    title: 'Sprint Intervals',
    category: 'TRAINING',
    day: 'Tuesday',
    time: '07:00',
    duration: '45 min',
    colorTint: 'bg-[#fce7f3]',
    subtitle: '6× 60m sprints',
  },
  {
    id: 't4',
    title: 'Applied Biostats',
    category: 'STUDYING',
    day: 'Tuesday',
    time: '13:00',
    duration: '90 min',
    colorTint: 'bg-[#fef08a]',
    subtitle: 'ANOVA dataset review',
  },
  {
    id: 't5',
    title: 'Hypertrophy (Bench)',
    category: 'TRAINING',
    day: 'Wednesday',
    time: '07:00',
    duration: '60 min',
    colorTint: 'bg-[#dcfce7]',
    subtitle: '5×5 • 80% 1RM',
  },
  {
    id: 't6',
    title: 'Physics II Lab',
    category: 'STUDYING',
    day: 'Wednesday',
    time: '15:00',
    duration: '120 min',
    colorTint: 'bg-[#e0f2fe]',
    subtitle: 'Electromagnetism report',
  },
  {
    id: 't7',
    title: 'Pool Flush & Mobility',
    category: 'RECOVERY',
    day: 'Thursday',
    time: '08:00',
    duration: '45 min',
    colorTint: 'bg-[#dcfce7]',
    subtitle: 'Zone 1 active flush • 45m',
  },
  {
    id: 't8',
    title: 'Olympic Lifting',
    category: 'TRAINING',
    day: 'Friday',
    time: '07:00',
    duration: '60 min',
    colorTint: 'bg-[#fce7f3]',
    subtitle: 'Power jerks & cleans',
  },
  {
    id: 't9',
    title: 'Academic Advisory',
    category: 'STUDYING',
    day: 'Friday',
    time: '14:00',
    duration: '30 min',
    colorTint: 'bg-[#fef08a]',
    subtitle: 'Degree check • 30m',
  },
  {
    id: 't10',
    title: 'Trail Run (14km)',
    category: 'TRAINING',
    day: 'Saturday',
    time: '08:00',
    duration: '75 min',
    colorTint: 'bg-[#ede9fe]',
    subtitle: 'Zone 2 steady pace',
  },
  {
    id: 't11',
    title: 'Weekly Meal Prep',
    category: 'OTHER',
    day: 'Sunday',
    time: '18:00',
    duration: '60 min',
    colorTint: 'bg-[#fed7aa]',
    subtitle: 'Nutrition setup for W39',
  }
];
